encoding: utf-8
baseurl: ""
url: "" 
markdown: kramdown
theme: minima 

plugins:
  - jekyll-redirect-from

title: Paul Viallard 
title-description: 
  - PhD Student
  - Machine Learning 
  - PAC-Bayesian Theory
  - Deep Learning
